environment:
  stage: environment
  image: docker
  variables:
    GIT_SUBMODULE_STRATEGY: none  # no need to fetch submodules
    CONTAINER_NAME: "$CI_REGISTRY/satoshilabs/trezor/trezor-firmware/environment"
  script:
    - 'pwd'
    - 'whoami'
